name: Deploy to ALT Linux

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ALT_LINUX_SSH_KEY }}

      - name: Verify SSH connection
        run: |
          echo "Testing connection to server..."
          ssh -o StrictHostKeyChecking=no ${{ secrets.ALT_LINUX_USER }}@${{ secrets.ALT_LINUX_IP }} "
            echo 'Successfully connected to:'
            hostname
            echo 'Docker version:'
            docker --version
            echo 'Git version:'
            git --version
          "

      - name: Deploy to ALT Linux
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.ALT_LINUX_USER }}@${{ secrets.ALT_LINUX_IP }} "
            cd ~/nginx-docker-project || exit 1
            echo 'Current directory:'
            pwd
            echo 'Updating code from GitHub...'
            git pull origin main
            echo 'Stopping existing containers...'
            docker-compose down || true
            echo 'Building and starting containers...'
            docker-compose up -d --build
            echo 'Deployment completed successfully!'
          "