name: Deploy to ALT Linux

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false  # Отключаем submodules

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0  # Правильное имя action
      with:
        ssh-private-key: ${{ secrets.ALT_LINUX_SSH_KEY }}  # Проверьте имя секрета

    - name: Deploy to ALT Linux
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.ALT_LINUX_USER }}@${{ secrets.ALT_LINUX_IP }} "
          cd ~/nginx-docker-project &&
          git pull origin main &&
          docker-compose down || true &&
          docker-compose up -d --build
        "